<html>
<body>
<?php
$fname=$_GET["fname"];
$lname=$_GET["lname"];
$address=$_GET["address"];
$city=$_GET["city"];
$state=$_GET["state"];
$country=$_GET["country"];
$zip=$_GET["zip"];
$tel=$_GET["tel"];
$mail=$_GET["mail"];
$address2=$_GET["address2"];
$city2=$_GET["city2"];
$state2=$_GET["state2"];
$country2=$_GET["country2"];
$zip2=$_GET["zip2"];
$date=$_GET["date"];
$subject=$_GET["subject"];
$description=$_GET["description"];
$img=$_GET['img'];
$conn=mysqli_connect("localhost","root","","NGO_database");
$sql="INSERT INTO user VALUES('$fname','$lname','$address','$city','$state','$country','$zip','$tel','$mail','$address2','$city2','$state2','$country2','$zip2','$date','$subject','$description')";
if($conn->query($sql)===TRUE)
{
echo "<h1>Thank You!</h1>";
}
?>
</body>
</html>
